sudo: required
language: node_js
node_js:
  - "node"
before_script:
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
  - cp .env.dist .env
deploy:
  - provider: script
    skip_cleanup: true
    script: HEROKU_API_KEY=$HEROKU_API_KEY bash scripts/deploy.sh
    on:
      branch: master