sudo: required
language: node_js
node_js:
  - "node"
before_script:
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
  - cp .env.dist .env
deploy:
  - provider: script
    script: bash script/deploy.sh
    on:
      branch: master